using UnityEngine;

namespace ProjectS.Combat.Player
{
    /// <summary>
    /// Runtime stat data is to keep track of the character's stats during gameplay.
    /// This should be generated by the CharacterData.
    /// </summary>
    public class RuntimeStatData 
    {
        
    }
}